/* =====================================================================
   VEREDA · DADOS (mocks ficcionais, internamente coerentes)
   ===================================================================== */

const BACIAS = [
  { id:'zona-mata', nome:'Zona da Mata', uf:'MG', unidade:'MG', semaforo:'verde',
    forecast:{ q1:+0.05, q2:+0.06, q3:+0.04 }, banda:0.03, acerto2T:72,
    pilares:{ P:0.00, E:+0.02, C:+0.04, A:+0.01 }, sinalClaro:true,
    cooperativa:'Itambé', cooperativaId:'itambe' },
  { id:'triangulo', nome:'Triângulo Mineiro', uf:'MG', unidade:'MG', semaforo:'amarelo',
    forecast:{ q1:+0.02, q2:+0.01, q3:-0.01 }, banda:0.07, acerto2T:51,
    pilares:{ P:-0.01, E:+0.02, C:-0.02, A:+0.01 }, sinalClaro:false,
    cooperativa:'CCPR', cooperativaId:'ccpr' },
  { id:'sul-minas', nome:'Sul de Minas', uf:'MG', unidade:'MG', semaforo:'verde',
    forecast:{ q1:+0.03, q2:+0.04, q3:+0.03 }, banda:0.035, acerto2T:69,
    pilares:{ P:0.00, E:+0.01, C:+0.03, A:0.00 }, sinalClaro:true,
    cooperativa:'Cooperativa Cooxupé Leite', cooperativaId:'cooxupe' },
  { id:'sul-goias', nome:'Sul de Goiás', uf:'GO', unidade:'GO', semaforo:'vermelho',
    forecast:{ q1:-0.04, q2:-0.05, q3:-0.03 }, banda:0.04, acerto2T:68,
    pilares:{ P:-0.01, E:-0.04, C:+0.01, A:-0.01 }, sinalClaro:true,
    cooperativa:'Cooperativa Comigo', cooperativaId:'comigo' },
  { id:'norte-pr', nome:'Norte do Paraná', uf:'PR', unidade:'PR', semaforo:'amarelo',
    forecast:{ q1:+0.01, q2:+0.02, q3:+0.02 }, banda:0.05, acerto2T:58,
    pilares:{ P:0.00, E:+0.02, C:0.00, A:0.00 }, sinalClaro:true,
    cooperativa:'Castrolanda', cooperativaId:'castrolanda' },
];

/* Detalhamento por região leiteira — ficha completa que abre no modal de detalhe */
const BACIAS_DETALHE = {
  'zona-mata':{
    cooperativa:'Cooperativa Itambé',
    municipios:['Juiz de Fora','Muriaé','Cataguases','Ubá','Leopoldina','São João Nepomuceno'],
    produtoresAtivos:148, produtoresSerie:[132,135,138,141,144,146,148],
    volumeMedioDia:'284.500 L/dia', volumeSerie:[262000,268000,272000,276000,279000,281000,284500],
    ccsMedio:412, ccsSerie:[345,360,375,388,395,402,412],
    cbtMedio:38, cbtSerie:[35,36,36,37,37,38,38],
    precoMedio:2.84, precoSerie:[2.62,2.68,2.71,2.74,2.78,2.81,2.84],
    cepeaSerie:[2.60,2.64,2.66,2.69,2.72,2.75,2.78],
    contrato:{
      inicio:'15/03/2022', vencimento:'14/03/2027',
      clausulaRevisao:'Revisão de preço trimestral · próxima janela em 12/08/2026',
      ultimaRenegociacao:'14/10/2025',
      bonificacao:'CCS<300: +R$ 0,08/L · CBT<50: +R$ 0,03/L · Fidelidade 12m: +R$ 0,02/L',
    },
    contato:{
      nome:'José Henrique Andrade', cargo:'Diretor de Captação · Itambé',
      email:'jh.andrade@itambe.com.br', telefone:'(31) 99841-2207',
      ultimoContato:'08/05/2026',
    },
    responsavelInterno:'Anderson Toledo · Gerente de Captação',
    inicioMonitoramento:'01/2023',
    fontes:['ERP de captação (romaneios diários)','Laudo lab. interno (CCS/CBT)','CEPEA/ESALQ (referência)','CHIRPS (chuva)','IBGE PPM (rebanho)'],
    notas:'Região âncora de qualidade da indústria. Sensível à seca de inverno (jun–set).',
  },
  'triangulo':{
    cooperativa:'CCPR · Cooperativa Central dos Produtores Rurais',
    municipios:['Uberaba','Uberlândia','Patrocínio','Araguari','Patos de Minas'],
    produtoresAtivos:92, produtoresSerie:[98,97,96,94,93,92,92],
    volumeMedioDia:'176.300 L/dia', volumeSerie:[182000,180000,179000,178000,177000,176500,176300],
    ccsMedio:368, ccsSerie:[340,348,355,360,365,366,368],
    cbtMedio:42, cbtSerie:[40,41,41,42,42,42,42],
    precoMedio:2.79, precoSerie:[2.64,2.68,2.72,2.74,2.76,2.78,2.79],
    cepeaSerie:[2.60,2.64,2.66,2.69,2.72,2.75,2.78],
    contrato:{
      inicio:'01/06/2021', vencimento:'31/05/2026',
      clausulaRevisao:'Revisão de preço semestral · próxima janela em 01/12/2026',
      ultimaRenegociacao:'02/12/2025',
      bonificacao:'CCS<350: +R$ 0,05/L · CBT<60: +R$ 0,02/L',
    },
    contato:{
      nome:'Marina Ribeiro Couto', cargo:'Gerente de Captação · CCPR',
      email:'marina.couto@ccpr.coop.br', telefone:'(34) 99732-8841',
      ultimoContato:'22/04/2026',
    },
    responsavelInterno:'Anderson Toledo · Gerente de Captação',
    inicioMonitoramento:'04/2023',
    fontes:['ERP de captação (romaneios diários)','Laudo lab. interno','CEPEA/ESALQ','Cocari (inteligência de mercado)'],
    notas:'Cooperativa concorrente (Cocari) ativa na rota desde 02/2026 pagando +R$ 0,04/L.',
  },
  'sul-minas':{
    cooperativa:'Cooxupé Leite',
    municipios:['Pouso Alegre','Varginha','Três Corações','São Lourenço','Itajubá'],
    produtoresAtivos:64, produtoresSerie:[60,61,62,62,63,64,64],
    volumeMedioDia:'118.700 L/dia', volumeSerie:[112000,113500,115000,116500,117500,118200,118700],
    ccsMedio:298, ccsSerie:[310,305,302,300,298,298,298],
    cbtMedio:34, cbtSerie:[36,35,35,34,34,34,34],
    precoMedio:2.86, precoSerie:[2.66,2.70,2.74,2.78,2.81,2.83,2.86],
    cepeaSerie:[2.60,2.64,2.66,2.69,2.72,2.75,2.78],
    contrato:{
      inicio:'01/01/2023', vencimento:'31/12/2027',
      clausulaRevisao:'Revisão anual · próxima janela em 01/01/2027',
      ultimaRenegociacao:'01/01/2026',
      bonificacao:'CCS<300: +R$ 0,10/L · Volume crescente: +R$ 0,03/L · Premium queijo: +R$ 0,05/L',
    },
    contato:{
      nome:'Eduardo Stein', cargo:'Diretor Comercial · Cooxupé Leite',
      email:'eduardo.stein@cooxupeleite.coop.br', telefone:'(35) 99918-7740',
      ultimoContato:'12/05/2026',
    },
    responsavelInterno:'Anderson Toledo · Gerente de Captação',
    inicioMonitoramento:'08/2023',
    fontes:['ERP de captação','Laudo lab. interno','CEPEA/ESALQ','INMET (estação Lavras)'],
    notas:'Qualidade premium consistente. Cooperativa investiu em assistência técnica em 2025.',
  },
  'sul-goias':{
    cooperativa:'Cooperativa Comigo',
    municipios:['Rio Verde','Jataí','Mineiros','Quirinópolis','Santa Helena de Goiás'],
    produtoresAtivos:71, produtoresSerie:[78,77,75,74,73,72,71],
    volumeMedioDia:'132.900 L/dia', volumeSerie:[145000,142000,140000,138000,136000,134000,132900],
    ccsMedio:445, ccsSerie:[395,410,420,428,436,442,445],
    cbtMedio:48, cbtSerie:[44,45,46,47,47,48,48],
    precoMedio:2.71, precoSerie:[2.58,2.62,2.66,2.69,2.70,2.71,2.71],
    cepeaSerie:[2.60,2.64,2.66,2.69,2.72,2.75,2.78],
    contrato:{
      inicio:'01/09/2022', vencimento:'31/08/2026',
      clausulaRevisao:'Revisão de preço trimestral · próxima janela em 01/09/2026',
      ultimaRenegociacao:'01/03/2026',
      bonificacao:'CCS<400: +R$ 0,04/L · Volume estável: +R$ 0,02/L',
    },
    contato:{
      nome:'Roberto Schneider', cargo:'Gerente de Captação · Comigo',
      email:'roberto.schneider@comigo.coop.br', telefone:'(64) 99647-3320',
      ultimoContato:'02/05/2026',
    },
    responsavelInterno:'Anderson Toledo · Gerente de Captação',
    inicioMonitoramento:'11/2023',
    fontes:['ERP de captação','Laudo lab. interno','CEPEA/ESALQ','CHIRPS (chuva)','B3 (milho futuro)'],
    notas:'Pressão de custo do milho. Câmbio favorável ao leite em pó importado em discussão.',
  },
  'norte-pr':{
    cooperativa:'Castrolanda',
    municipios:['Castro','Carambeí','Ponta Grossa','Arapoti','Tibagi'],
    produtoresAtivos:54, produtoresSerie:[50,51,52,52,53,53,54],
    volumeMedioDia:'168.400 L/dia', volumeSerie:[160000,162000,163500,165000,166500,167500,168400],
    ccsMedio:325, ccsSerie:[330,328,326,325,324,325,325],
    cbtMedio:36, cbtSerie:[38,37,36,36,36,36,36],
    precoMedio:2.82, precoSerie:[2.64,2.68,2.72,2.75,2.78,2.80,2.82],
    cepeaSerie:[2.60,2.64,2.66,2.69,2.72,2.75,2.78],
    contrato:{
      inicio:'15/07/2022', vencimento:'14/07/2027',
      clausulaRevisao:'Revisão semestral · próxima janela em 15/01/2027',
      ultimaRenegociacao:'15/01/2026',
      bonificacao:'CCS<350: +R$ 0,06/L · CBT<50: +R$ 0,02/L · Fidelidade: +R$ 0,02/L',
    },
    contato:{
      nome:'Henk van der Berg', cargo:'Gerente de Captação · Castrolanda',
      email:'henk.berg@castrolanda.coop.br', telefone:'(42) 99837-6614',
      ultimoContato:'28/04/2026',
    },
    responsavelInterno:'Anderson Toledo · Gerente de Captação',
    inicioMonitoramento:'02/2024',
    fontes:['ERP de captação','Laudo lab. interno','CEPEA/ESALQ','IBGE PPM','Frísia (inteligência de mercado)'],
    notas:'Genética holandesa + manejo industrializado. Estabilidade alta, margem fina.',
  },
};

/* Resultado fixo do "AI import" do fluxo de criação de nova região (demo) */
const IMPORTACAO_DEMO = {
  arquivo:'Aurora_oeste_sc_36meses.xlsx',
  tamanho:'3,4 MB',
  linhas:1842,
  abas:['Romaneios diarios','Laudos laboratorio','Contratos','Tabela de preco','Bonificacao qualidade'],
  steps:[
    { t:'Lendo arquivo Aurora_oeste_sc_36meses.xlsx (3,4 MB)…',                                  delay:600  },
    { t:'Detectando estrutura: 5 abas, 1.842 linhas, 22 colunas.',                               delay:700  },
    { t:'Mapeando colunas para o schema Vereda (data · produtor · volume · CCS · CBT · preço).', delay:900  },
    { t:'Cruzando CNPJ da cooperativa com base pública (Receita + OCB) → Cooperativa Central Aurora Alimentos Ltda.', delay:1000 },
    { t:'Identificando região leiteira pela distribuição de municípios → Oeste de Santa Catarina · SC.', delay:950 },
    { t:'Não há sobreposição com regiões cadastradas — esta é uma nova bacia para o Vereda.',    delay:700  },
    { t:'Consolidando 36 meses de série · 92 produtores ativos · contrato vigente até 30/09/2027.', delay:800 },
    { t:'Pronto. Pré-visualização da nova região leiteira abaixo.',                              delay:500  },
  ],
  resultado:{
    id:'oeste-sc',
    nome:'Oeste de Santa Catarina',
    uf:'SC',
    cooperativa:'Cooperativa Aurora',
    produtoresAtivos:92,
    volumeMedioDia:'196.800 L/dia',
    municipios:7,
    contratoVencimento:'30/09/2027',
    ccsMedio:298,
    precoMedio:'R$ 2,91/L',
    aviso:'Nova bacia — não há sobreposição com regiões cadastradas. A IA precisa de pelo menos 6 meses de série para gerar previsão com confiança; nesse intervalo a região entra em "modo observação" no Painel.',
  },
};

/* Payload aplicado ao confirmar o cadastro: vira um card no Painel e uma ficha em BACIAS_DETALHE */
const NOVA_REGIAO_PAYLOAD = {
  bacia:{
    id:'oeste-sc', nome:'Oeste de Santa Catarina', uf:'SC', unidade:'SC',
    semaforo:'amarelo',
    forecast:{ q1:+0.03, q2:+0.04, q3:+0.03 }, banda:0.08, acerto2T:null,
    pilares:{ P:0.00, E:+0.02, C:+0.01, A:+0.01 }, sinalClaro:false,
    cooperativa:'Cooperativa Aurora', cooperativaId:'aurora',
    novaRegiao:true,
  },
  detalhe:{
    cooperativa:'Cooperativa Central Aurora Alimentos Ltda.',
    municipios:['Chapecó','Concórdia','Xanxerê','Pinhalzinho','São Miguel do Oeste','Maravilha','Seara'],
    produtoresAtivos:92, produtoresSerie:[78,81,83,85,87,90,92],
    volumeMedioDia:'196.800 L/dia', volumeSerie:[172000,176000,181000,186000,190000,193500,196800],
    ccsMedio:298, ccsSerie:[315,310,306,303,301,299,298],
    cbtMedio:33, cbtSerie:[36,35,34,34,33,33,33],
    precoMedio:2.91, precoSerie:[2.70,2.74,2.78,2.82,2.86,2.89,2.91],
    cepeaSerie:[2.60,2.64,2.66,2.69,2.72,2.75,2.78],
    contrato:{
      inicio:'01/10/2022', vencimento:'30/09/2027',
      clausulaRevisao:'Revisão de preço quadrimestral · próxima janela em 01/10/2026',
      ultimaRenegociacao:'01/06/2026',
      bonificacao:'CCS<300: +R$ 0,10/L · CBT<40: +R$ 0,04/L · Volume crescente: +R$ 0,03/L · Premium queijo: +R$ 0,04/L',
    },
    contato:{
      nome:'Daiana Fischer Hoffmann', cargo:'Gerente de Captação · Aurora Oeste',
      email:'daiana.hoffmann@auroraalimentos.com.br', telefone:'(49) 99812-4470',
      ultimoContato:'19/05/2026',
    },
    responsavelInterno:'Anderson Toledo · Gerente de Captação',
    inicioMonitoramento:'05/2026 · nova',
    fontes:['ERP de captação (planilha importada)','Laudo lab. interno','CEPEA/ESALQ','CHIRPS (chuva)','Epagri (assistência técnica SC)'],
    notas:'Bacia nova no Vereda. Genética holandesa + clima frio favorecem qualidade. Forte concorrência da Tirol e Piracanjuba na região.',
  },
};

const PILAR_NOME = { P:'Político', E:'Econômico', C:'Climático', A:'Agropecuário' };

const RECOMENDACAO_ZONA_MATA = {
  alavanca:'Antecipe em 30 dias a renegociação de contrato com a cooperativa Itambé e direcione mais volume de compra para esta região.',
  prob:70, spreadMin:+0.03, spreadMax:+0.07,
  // Plano de ação concreto — o "como fazer" por trás da alavanca
  plano:{
    janelaIdeal:'08/06/2026 a 22/06/2026',
    janelaJustificativa:'Cláusula de revisão trimestral abre em 12/08/2026. Negociar 30–60 dias antes evita pressão de prazo e dá margem pra ajustar volume contratado antes do pico da seca.',
    acoes:[
      { titulo:'Convocar reunião com José Henrique Andrade (Diretor de Captação · Itambé)', detalhe:'Apresentar projeção CHIRPS de oferta regional −6% e propor antecipação da janela de revisão de preço.' },
      { titulo:'Negociar aumento de volume contratado em +12% no trimestre 08–10/2026', detalhe:'Volume atual: 284.500 L/dia · proposta: 318.640 L/dia. Compensa o aperto previsto de oferta regional.' },
      { titulo:'Revisar bonificação por qualidade (CCS/CBT)', detalhe:'CCS regional subindo (+18% no trimestre). Travar tier CCS<300 em +R$ 0,10/L incentiva o produtor a investir em manejo antes do agravamento da seca.' },
      { titulo:'Documentar premissa climática no contrato', detalhe:'Incluir cláusula de gatilho: se chuva acumulada (CHIRPS) ficar >25% abaixo da média em jul–ago, abre janela extraordinária de renegociação.' },
    ],
    impactoEstimado:{
      ganhoLitro:'+R$ 0,05/L (mediana da faixa +R$ 0,03 a +R$ 0,07)',
      volumeMensal:'8,5 milhões de litros (284.500 L/dia × 30 dias)',
      impactoTrimestre:'R$ 1,27 milhão de margem adicional no trimestre vs. cenário de não agir',
      premissa:'Considera spread de preço estimado pela IA × volume contratado pós-renegociação. Sensível a câmbio (R$ 5,40) e premissa climática (neutro).',
    },
    naoFazer:[
      'Não conceder aumento de bônus antes da virada climática confirmada — espera mais 30 dias de leitura CHIRPS.',
      'Não estender contrato vigente sem cláusula de gatilho climático.',
    ],
    fontesAcao:[
      { nome:'Itambé · ERP de captação', detalhe:'Volume contratado e histórico de revisão.' },
      { nome:'CHIRPS', detalhe:'Projeção de chuva acumulada por satélite.' },
      { nome:'CEPEA/ESALQ', detalhe:'Preço de referência pra modelar spread.' },
    ],
  },
  // Metodologia exposta ao usuário
  metodologia:{
    resumo:'A IA cruza 4 pilares (Climático, Econômico, Agropecuário, Político) e cada pilar entra com um peso em R$/litro. A soma dos pilares ativos = ganho esperado vs. CEPEA. O fator Político fica em quarentena (peso zero) até virar fato consumado em Diário Oficial.',
    janelaPrevisao:'9 meses · ensemble SARIMAX (séries temporais) + LightGBM (não-linearidade)',
    calibracao:'Recalibrada a cada ciclo trimestral contra realizados. Acerto histórico em 6 meses para a Zona da Mata: 72%.',
  },
  drivers:[
    { pilar:'Climático', sigla:'C', valor:+0.04,
      detalhe:'Chuva acumulada 18% abaixo da média dos últimos 10 anos na região — projeção de menor oferta regional de leite na janela de 6–9 meses.',
      dadoBruto:'Acumulado mar–mai/2026: 142 mm vs. média 10 anos 173 mm (Δ −18%). Projeção CHIRPS jun–ago/2026: 38 mm vs. média 52 mm (−27%).',
      comparacao:'Padrão similar ao trimestre seco de 2014, quando oferta regional caiu 8% e preço subiu R$ 0,07/L.',
      fonte:'CHIRPS / NASA POWER', url:'https://www.chc.ucsb.edu/data/chirps',
      atualizadoEm:'27/05/2026' },
    { pilar:'Econômico', sigla:'E', valor:+0.02,
      detalhe:'Dólar a R$ 5,40 e milho futuro +3% pressionam o custo de produção do produtor e sustentam o preço pago pelo leite.',
      dadoBruto:'Dólar PTAX 28/05/2026: R$ 5,4087/USD. Milho futuro B3 (CCMK26): R$ 71,40/saca (+3,1% no mês).',
      comparacao:'Dólar acima de R$ 5,30 historicamente correlaciona com preço pago ao produtor +R$ 0,02 a +R$ 0,04/L vs. CEPEA.',
      fonte:'BCB-SGS / B3 (milho)', url:'https://www3.bcb.gov.br/sgspub/',
      atualizadoEm:'29/05/2026' },
    { pilar:'Agropecuário', sigla:'A', valor:+0.01,
      detalhe:'Rebanho estável (IBGE PPM); contagem de células somáticas (CCS) subindo na seca — sinaliza pressão de qualidade do leite.',
      dadoBruto:'Rebanho Zona da Mata 2024 (IBGE PPM): 312 mil cabeças (estável vs. 2023). CCS médio regional últimos 90 dias: 388 céls/mL (vs. 345 no mesmo período de 2025, +12%).',
      comparacao:'Aumento de CCS na entressafra é típico, mas a curva atual está 1 mês adiantada — sugere efeito climático antecipado.',
      fonte:'IBGE PPM / laboratório interno', url:'https://www.ibge.gov.br/',
      atualizadoEm:'25/05/2026' },
    { pilar:'Político', sigla:'P', valor:0.00, quarentena:true,
      detalhe:'Possível mudança de alíquota do leite em pó importado em discussão no Mercosul — observado, mas não entra no cálculo da IA até virar fato.',
      dadoBruto:'PL 1.247/2026 em discussão na Câmara propõe redução de alíquota TEC do leite em pó de 28% para 16% pra produtos Mercosul. Última movimentação: relatoria em 18/05/2026.',
      comparacao:'Se aprovado e em vigor, simulações sugerem pressão de −R$ 0,03 a −R$ 0,05/L no preço doméstico. Até virar lei, peso na IA = 0.',
      fonte:'MAPA / Diário Oficial', url:'https://www.gov.br/agricultura/',
      atualizadoEm:'18/05/2026' },
  ],
};

/* Planos de ação por região (Zona da Mata é o RECOMENDACAO_ZONA_MATA acima) */
const PLANOS_POR_BACIA = {
  'triangulo':{
    alavanca:'Não comprometa volume adicional nesta região no próximo trimestre. Foque em reter os produtores categoria Atenção antes que a Cocari pegue a base.',
    prob:51, spreadMin:-0.06, spreadMax:+0.08,
    plano:{
      janelaIdeal:'10/06/2026 a 25/06/2026',
      janelaJustificativa:'Cocari (cooperativa concorrente) está pagando +R$ 0,04/L na região desde fev/2026. Esperar mais 30 dias arrisca perda gradual de produtores categoria Atenção sem chance de reação.',
      acoes:[
        { titulo:'Visitar Granja Três Irmãos e os outros 3 produtores categoria Atenção em 15 dias', detalhe:'Pedido de segunda via de contrato em 18/04 é sinal forte de comparação de propostas. Visita reverte 60–70% dessas tendências em janela de até 30 dias.' },
        { titulo:'Lançar bônus de fidelidade temporário (90 dias)', detalhe:'+R$ 0,02/L para produtores com 24+ meses de contrato — cobre o gap vs. Cocari sem virar gatilho permanente.' },
        { titulo:'Não renegociar volume contratado com a CCPR neste trimestre', detalhe:'Sinal misto da IA (faixa larga, acerto 51%) — não é hora de comprometer alocação de capital. Mantenha a posição até o próximo ciclo.' },
        { titulo:'Pedir à CCPR boletim semanal de inteligência de mercado', detalhe:'Marina Couto já mantém esse boletim internamente. Visibilidade contínua sobre Cocari vale mais que decisão pontual agora.' },
      ],
      impactoEstimado:{
        ganhoLitro:'Defensivo · valor em não perder',
        volumeMensal:'5,3 milhões de L/mês (176.300 L/dia × 30 dias)',
        impactoTrimestre:'Evitar perda estimada de R$ 380 mil em volume captado',
        premissa:'Considera 8% de churn de produtores Atenção se ação não acontecer (taxa histórica em regiões com concorrente ativo na rota há >90 dias).',
      },
      naoFazer:[
        'Não conceder bônus permanente — risco de virar piso fixo.',
        'Não antecipar revisão contratual com a CCPR — sinal não é claro o suficiente.',
        'Não comprometer aumento de volume contratado neste ciclo.',
      ],
    },
    metodologia:{
      resumo:'A IA tem baixa confiança nesta região por causa do conflito entre sinal econômico positivo (+R$ 0,02 do câmbio/milho) e sinal climático negativo (−R$ 0,02 de oferta acima da média). Faixa de previsão fica larga (±0,07).',
      janelaPrevisao:'9 meses · ensemble SARIMAX + LightGBM',
      calibracao:'Acerto histórico em 6 meses para o Triângulo: 51%. Sinal de pouca confiança fica visível no painel.',
    },
    drivers:[
      { pilar:'Climático', sigla:'C', valor:-0.02,
        detalhe:'Chuva acumulada acima da média no Triângulo — projeção de oferta regional levemente maior do que o esperado.',
        dadoBruto:'Acumulado mar–mai/2026: 198 mm vs. média 10 anos 175 mm (+13%). Projeção CHIRPS jun–ago: 65 mm vs. média 58 mm (+12%).',
        comparacao:'Excesso de chuva moderado historicamente reduz o preço pago em R$ 0,02–0,03/L vs. CEPEA.',
        fonte:'CHIRPS / NASA POWER', url:'https://www.chc.ucsb.edu/data/chirps', atualizadoEm:'27/05/2026' },
      { pilar:'Econômico', sigla:'E', valor:+0.02,
        detalhe:'Câmbio elevado sustenta preço pago, mas o efeito é parcialmente neutralizado pela maior oferta regional.',
        dadoBruto:'Dólar PTAX 28/05/2026: R$ 5,4087/USD. Milho futuro B3 (CCMK26): R$ 71,40/saca (+3,1% no mês).',
        comparacao:'Em regiões de sinal misto, o pilar econômico costuma dominar quando a oferta é estável — não é o caso aqui.',
        fonte:'BCB-SGS / B3 (milho)', url:'https://www3.bcb.gov.br/sgspub/', atualizadoEm:'29/05/2026' },
      { pilar:'Agropecuário', sigla:'A', valor:+0.01,
        detalhe:'Rebanho regional estável; CCS médio em piso histórico (368 céls/mL).',
        dadoBruto:'Rebanho Triângulo Mineiro 2024 (IBGE PPM): 198 mil cabeças (+1,2% vs. 2023). CCS médio últimos 90 dias: 368 céls/mL.',
        comparacao:'CCS abaixo de 400 sustenta tier de bonificação atual, mas não tem efeito de margem adicional.',
        fonte:'IBGE PPM / laboratório interno', url:'https://www.ibge.gov.br/', atualizadoEm:'25/05/2026' },
      { pilar:'Político', sigla:'P', valor:0.00, quarentena:true,
        detalhe:'Mesma pauta Mercosul observada nacionalmente. Quarentena permanente.',
        dadoBruto:'PL 1.247/2026 em discussão na Câmara — TEC do leite em pó. Última movimentação: relatoria em 18/05/2026.',
        comparacao:'Sem efeito direto enquanto não virar lei. Peso na IA = 0.',
        fonte:'MAPA / Diário Oficial', url:'https://www.gov.br/agricultura/', atualizadoEm:'18/05/2026' },
    ],
  },
  'sul-minas':{
    alavanca:'Antecipe conversa com a Cooxupé Leite e proponha aumento de +15% no volume contratado anual. Sul de Minas é o melhor par risco-retorno do portfólio atual.',
    prob:69, spreadMin:+0.01, spreadMax:+0.07,
    plano:{
      janelaIdeal:'01/07/2026 a 15/07/2026',
      janelaJustificativa:'Revisão anual de contrato com a Cooxupé Leite abre em 01/01/2027. Conversa preliminar 6 meses antes pega Eduardo Stein no fim do ciclo de planejamento da cooperativa.',
      acoes:[
        { titulo:'Reunião com Eduardo Stein (Diretor Comercial · Cooxupé Leite)', detalhe:'Apresentar projeção de demanda interna +15% para 2027 + plano de expansão de bonificação tier premium para incentivar manejo confinado.' },
        { titulo:'Negociar volume anual +15% (volume atual 118.700 L/dia → meta 136.500 L/dia)', detalhe:'Cooperativa já investiu em assistência técnica em 2025 — base de produtores tem capacidade técnica pra absorver crescimento.' },
        { titulo:'Travar tier premium CCS<300 em +R$ 0,12/L', detalhe:'CCS médio regional já está em 298 (abaixo do limite premium). Pequeno aumento do tier vira retenção barata.' },
        { titulo:'Avaliar contrato 5 anos com cláusula de revisão anual', detalhe:'Cooxupé tem perfil de longo prazo. Contrato longo reduz pressão de renegociação anual e libera capital pra outras frentes.' },
      ],
      impactoEstimado:{
        ganhoLitro:'+R$ 0,04/L (mediana da faixa +R$ 0,01 a +R$ 0,07)',
        volumeMensal:'4,1 milhões de L/mês após expansão (136.500 L/dia × 30 dias)',
        impactoTrimestre:'R$ 491 mil de margem adicional no trimestre pós-expansão',
        premissa:'Considera execução em 01/01/2027. Sensível ao câmbio (R$ 5,40) e à premissa de absorção de qualidade pelo mercado interno.',
      },
      naoFazer:[
        'Não pressionar prazo — Cooxupé responde mal a urgência negocial.',
        'Não envolver outros tiers de bonificação na mesma conversa — mantenha foco no volume + CCS premium.',
        'Não comprometer logística (rotas, frota) sem confirmação da operação interna.',
      ],
    },
    metodologia:{
      resumo:'Região de sinal claro e consistente: oferta sob controle, qualidade premium, contrato vigente até 2027. Combinação ideal pra crescer volume contratado.',
      janelaPrevisao:'9 meses · ensemble SARIMAX + LightGBM',
      calibracao:'Acerto histórico em 6 meses para Sul de Minas: 69%.',
    },
    drivers:[
      { pilar:'Climático', sigla:'C', valor:+0.03,
        detalhe:'Chuva levemente abaixo da média + INMET indica entressafra branda — oferta projetada estável.',
        dadoBruto:'Acumulado mar–mai/2026: 162 mm vs. média 10 anos 168 mm (−4%). Estação INMET Lavras: padrão normal.',
        comparacao:'Estabilidade climática histórica em Sul de Minas correlaciona com prêmio de preço de R$ 0,02–0,04/L vs. CEPEA.',
        fonte:'CHIRPS / INMET', url:'https://www.chc.ucsb.edu/data/chirps', atualizadoEm:'27/05/2026' },
      { pilar:'Econômico', sigla:'E', valor:+0.01,
        detalhe:'Câmbio sustenta preço base, mas demanda interna premium (queijos) é o driver principal.',
        dadoBruto:'Demanda de queijos premium MG +8% em 12 meses (dados ABIQ). Preço pago Cooxupé Leite: R$ 2,86/L (R$ 0,08 acima do CEPEA).',
        comparacao:'Mercado de queijos premium tem alavancagem maior que o leite UHT — efeito não captado pelo CEPEA.',
        fonte:'BCB-SGS / ABIQ', url:'https://www3.bcb.gov.br/sgspub/', atualizadoEm:'29/05/2026' },
      { pilar:'Agropecuário', sigla:'A', valor:0.00,
        detalhe:'Qualidade do leite consistentemente premium. Rebanho expandiu 6% em 2024.',
        dadoBruto:'CCS médio regional 12 meses: 298 céls/mL. Rebanho 2024 (IBGE PPM): 287 mil cabeças (+6,2% vs. 2023).',
        comparacao:'Único caso entre as 5 regiões com CCS médio abaixo do limite premium 300.',
        fonte:'IBGE PPM / laboratório interno', url:'https://www.ibge.gov.br/', atualizadoEm:'25/05/2026' },
      { pilar:'Político', sigla:'P', valor:0.00, quarentena:true,
        detalhe:'Sem pauta política específica afetando a região. Quarentena permanente.',
        dadoBruto:'Pauta Mercosul (TEC) é nacional. Sem impacto regional específico mapeado.',
        comparacao:'—',
        fonte:'MAPA / Diário Oficial', url:'https://www.gov.br/agricultura/', atualizadoEm:'18/05/2026' },
    ],
  },
  'sul-goias':{
    alavanca:'Postura defensiva: mantenha o volume contratado, não conceda aumentos de bônus e prepare plano B com a Cooperativa Comigo. Sul de Goiás vai apertar nos próximos 6 meses.',
    prob:68, spreadMin:-0.09, spreadMax:-0.01,
    plano:{
      janelaIdeal:'NÃO antecipar · esperar revisão trimestral em 01/09/2026',
      janelaJustificativa:'IA tem 68% de confiança no sinal negativo. Antecipar conversa expõe a indústria — melhor deixar a cooperativa vir com a próxima janela formal e barganhar com a leitura na mão.',
      acoes:[
        { titulo:'Não conceder bônus extra à Cooperativa Comigo neste ciclo', detalhe:'CCS subindo 13% nos últimos 90 dias (445 céls/mL atual) sugere qualidade pressionada — não premiar quando a base de qualidade está se deteriorando.' },
        { titulo:'Revisar contratos de menor volume na região e considerar não-renovar até 12 produtores Atenção', detalhe:'Concentração em produtores OK reduz exposição. Capital liberado vai pra reforçar Sul de Minas e Zona da Mata.' },
        { titulo:'Preparar plano B com Sul de Minas e Norte do Paraná', detalhe:'Reduzir 8% do volume contratado em Sul de Goiás e realocar para regiões com sinal positivo de IA. Início da realocação em out/2026.' },
        { titulo:'Monitorar B3 (milho) e PL 1.247 da TEC do leite em pó semanalmente', detalhe:'Dois gatilhos: milho >R$ 80/saca ou aprovação da TEC, qualquer um, vira sinal de saída antecipada de Sul de Goiás.' },
      ],
      impactoEstimado:{
        ganhoLitro:'Defensivo · −R$ 0,05/L (mediana da faixa −R$ 0,09 a −R$ 0,01)',
        volumeMensal:'4,0 milhões de L/mês (132.900 L/dia × 30 dias)',
        impactoTrimestre:'Evitar perda estimada de R$ 595 mil ao manter postura defensiva',
        premissa:'Considera que o cenário não-defensivo levaria a aumento de bônus de +R$ 0,03/L sem ganho de margem. Premissa de câmbio R$ 5,40 e milho B3 estável.',
      },
      naoFazer:[
        'Não antecipar a renegociação contratual — ela vem em 01/09.',
        'Não conceder aumento de tier de bonificação enquanto CCS estiver subindo.',
        'Não cortar produtores OK por engano — limpe Atenção primeiro.',
      ],
    },
    metodologia:{
      resumo:'Sinal claramente negativo: pressão climática + câmbio favorecendo leite em pó importado + CCS subindo. Faixa estreita (banda ±0,04) com 68% de confiança no sinal de pressão.',
      janelaPrevisao:'9 meses · ensemble SARIMAX + LightGBM',
      calibracao:'Acerto histórico em 6 meses para Sul de Goiás: 68%.',
    },
    drivers:[
      { pilar:'Climático', sigla:'C', valor:+0.01,
        detalhe:'Padrão climático neutro. Sem efeito significativo de oferta projetada.',
        dadoBruto:'Acumulado mar–mai/2026: 174 mm vs. média 10 anos 180 mm (−3%). CHIRPS projeção jun–ago: dentro da banda histórica.',
        comparacao:'Sem padrão de seca ou excesso de chuva identificado.',
        fonte:'CHIRPS / NASA POWER', url:'https://www.chc.ucsb.edu/data/chirps', atualizadoEm:'27/05/2026' },
      { pilar:'Econômico', sigla:'E', valor:-0.04,
        detalhe:'Câmbio + custo do milho favorecem leite em pó importado. Pressão direta no preço doméstico.',
        dadoBruto:'Dólar PTAX 28/05/2026: R$ 5,4087/USD. Milho futuro B3 (CCMK26): R$ 71,40/saca (+3,1%). Importação de leite em pó +14% nos últimos 90 dias (SECEX).',
        comparacao:'Cenário similar ao 1º semestre de 2018 — preço pago caiu R$ 0,06/L em 4 meses.',
        fonte:'BCB-SGS / SECEX / B3', url:'https://www3.bcb.gov.br/sgspub/', atualizadoEm:'29/05/2026' },
      { pilar:'Agropecuário', sigla:'A', valor:-0.01,
        detalhe:'CCS regional subindo, sinaliza pressão de qualidade. Rebanho estável.',
        dadoBruto:'CCS médio últimos 90 dias: 445 céls/mL (+12,7% vs. mesmo período 2025). Rebanho 2024 (IBGE PPM): 165 mil cabeças (estável).',
        comparacao:'CCS acima de 400 sinaliza pressão de qualidade pré-seca atípica.',
        fonte:'IBGE PPM / laboratório interno', url:'https://www.ibge.gov.br/', atualizadoEm:'25/05/2026' },
      { pilar:'Político', sigla:'P', valor:0.00, quarentena:true,
        detalhe:'Pauta Mercosul (TEC) particularmente relevante para esta região — leite em pó importado da Argentina e Paraguai entra por aqui.',
        dadoBruto:'PL 1.247/2026: redução de TEC do leite em pó 28% → 16%. Última movimentação: relatoria em 18/05/2026. Sul de Goiás importa 38% do leite em pó MERCOSUL.',
        comparacao:'Se aprovado, pressão adicional estimada de −R$ 0,03 a −R$ 0,05/L na região. Quarentena: peso = 0 até virar lei.',
        fonte:'MAPA / SECEX', url:'https://www.gov.br/agricultura/', atualizadoEm:'18/05/2026' },
    ],
  },
  'norte-pr':{
    alavanca:'Mantenha o ritmo atual de captação e use o próximo trimestre para explorar relacionamento de longo prazo com a Castrolanda. Sinal positivo de baixa magnitude — ação calma.',
    prob:58, spreadMin:-0.03, spreadMax:+0.07,
    plano:{
      janelaIdeal:'15/11/2026 a 30/11/2026',
      janelaJustificativa:'Revisão semestral da Castrolanda abre em 15/01/2027. 60 dias antes é janela ideal para construir conversa de longo prazo sem pressão imediata.',
      acoes:[
        { titulo:'Manter visitas técnicas mensais', detalhe:'Castrolanda mantém perfil de estabilidade alta. Não há sinal forte de risco — frequência de relacionamento é o que sustenta a posição.' },
        { titulo:'Iniciar diálogo sobre contrato de longo prazo (5+ anos)', detalhe:'Henk van der Berg tem perfil de planejamento longo. Conversa de antecipação de horizonte traz previsibilidade para os 2 lados.' },
        { titulo:'Avaliar bonificação por CBT premium (<40)', detalhe:'CBT médio regional já em 36 — tier premium novo de R$ 0,03/L pode amarrar produtores premium sem grande custo marginal.' },
        { titulo:'Não comprometer mudança estrutural sem nova rodada de dado', detalhe:'Sinal de IA é de baixa magnitude (+R$ 0,02/L em 6 meses). Não justifica mudança grande de alocação — só ajuste fino.' },
      ],
      impactoEstimado:{
        ganhoLitro:'+R$ 0,02/L (mediana da faixa −R$ 0,03 a +R$ 0,07)',
        volumeMensal:'5,0 milhões de L/mês (168.400 L/dia × 30 dias)',
        impactoTrimestre:'R$ 303 mil de margem adicional no trimestre se mantida a posição',
        premissa:'Considera execução do plano sem mudança estrutural. Sensível à premissa de câmbio R$ 5,40 e estabilidade do rebanho holandês.',
      },
      naoFazer:[
        'Não comprometer volume adicional além da capacidade atual da Castrolanda.',
        'Não pressionar prazo — relacionamento de longo prazo é o ativo aqui.',
        'Não introduzir bonificações novas além do CBT premium.',
      ],
    },
    metodologia:{
      resumo:'Sinal positivo claro mas de baixa magnitude (+R$ 0,02/L). Acerto histórico de 58% reflete que a região tem padrão estável — não há grandes mudanças pra prever, e o modelo erra mais quando o sinal é pequeno.',
      janelaPrevisao:'9 meses · ensemble SARIMAX + LightGBM',
      calibracao:'Acerto histórico em 6 meses para Norte do Paraná: 58%. Menor da carteira por baixa amplitude do sinal.',
    },
    drivers:[
      { pilar:'Climático', sigla:'C', valor:0.00,
        detalhe:'Padrão climático típico de PR. Estabilidade alta no histórico.',
        dadoBruto:'Acumulado mar–mai/2026: 168 mm vs. média 10 anos 172 mm (−2%). CHIRPS projeção jun–ago: dentro da banda histórica.',
        comparacao:'Norte do PR é a região climaticamente mais estável da carteira.',
        fonte:'CHIRPS / NASA POWER', url:'https://www.chc.ucsb.edu/data/chirps', atualizadoEm:'27/05/2026' },
      { pilar:'Econômico', sigla:'E', valor:+0.02,
        detalhe:'Câmbio sustenta preço base. Custo do milho favorece a região (PR é grande produtor).',
        dadoBruto:'Dólar PTAX 28/05/2026: R$ 5,4087/USD. Milho futuro B3 (CCMK26): R$ 71,40/saca. PR responde por 22% da produção nacional de milho — vantagem logística.',
        comparacao:'Margem de produtor PR aguenta câmbio +20% sem repasse, dado vantagem logística do milho.',
        fonte:'BCB-SGS / CONAB', url:'https://www3.bcb.gov.br/sgspub/', atualizadoEm:'29/05/2026' },
      { pilar:'Agropecuário', sigla:'A', valor:0.00,
        detalhe:'Qualidade do leite premium consistente. Rebanho holandês com manejo industrializado.',
        dadoBruto:'CCS médio últimos 90 dias: 325 céls/mL. CBT médio: 36 (UFC ×10³/mL). Rebanho 2024 (IBGE PPM): 142 mil cabeças (+2,8%).',
        comparacao:'Padrão estável historicamente. Sem efeito de margem adicional.',
        fonte:'IBGE PPM / laboratório interno', url:'https://www.ibge.gov.br/', atualizadoEm:'25/05/2026' },
      { pilar:'Político', sigla:'P', valor:0.00, quarentena:true,
        detalhe:'Pauta Mercosul (TEC) com efeito moderado por logística PR. Quarentena permanente.',
        dadoBruto:'PL 1.247/2026 em discussão. Norte do PR recebe leite em pó importado pelo porto de Paranaguá.',
        comparacao:'Se aprovado, efeito estimado em −R$ 0,02/L. Quarentena: peso = 0.',
        fonte:'MAPA / Diário Oficial', url:'https://www.gov.br/agricultura/', atualizadoEm:'18/05/2026' },
    ],
  },
};

const HISTORICO_ZONA_MATA = [
  { data:'10/05/2026', alavanca:'Antecipar renegociação Itambé',     decisao:'Aceito',   realizado:+0.05, acertou:true },
  { data:'02/04/2026', alavanca:'Priorizar volume na Zona da Mata',  decisao:'Aceito',   realizado:+0.04, acertou:true },
  { data:'18/02/2026', alavanca:'Revisar bônus por qualidade',       decisao:'Ajustado', realizado:+0.02, acertou:true },
  { data:'07/01/2026', alavanca:'Manter mix atual',                  decisao:'Recusado', realizado:-0.01, acertou:false },
];

const PRODUTORES = [
  {
    id:1, nome:'Sítio Boa Vista', bacia:'Zona da Mata',
    categoria:'Alto', tendencia:'subindo', sobControle:false,
    riskScore:78, confianca:'alta', volumeMedio:'3.450 L/dia',
    proprietario:'Carlos Henrique Vasconcelos', cpf:'***.418.302-23',
    municipio:'Muriaé · MG', areaHa:42, vinculo:'cooperativa',
    rebanho:{ leiteiras:38, secas:7, raca:'Holandês × Gir (3/4)', regime:'Semiconfinado' },
    contrato:{
      inicio:'15/03/2024', vencimento:'14/03/2027',
      precoBase:2.78, bonificacaoAtual:'CCS<300: +R$ 0,08/L (não atinge desde fev/2026)',
      ultimaRevisaoBonificacao:'14/06/2025',
    },
    motivo:'Volume em queda + qualidade do leite (CCS) piorando + concorrente ativa na rota.',
    sinais:[
      { label:'Volume caiu 18% em 60 dias', peso:+24,
        fonte:'ERP de captação · romaneios diários',
        detalhe:'Média 60 dias atrás: 4.200 L/dia → últimos 30 dias: 3.450 L/dia (Δ −750 L/dia, −17,9%).',
        data:'calculado em 28/05/2026' },
      { label:'CCS acima do limite em 3 leituras consecutivas', peso:+18,
        fonte:'Laudo lab. interno (LabAgro Juiz de Fora)',
        detalhe:'510 (mar/26) · 590 (abr/26) · 640 (mai/26) — limite legal IN 76: 500 céls/mL.',
        data:'última leitura 22/05/2026' },
      { label:'Italac (concorrente) reportada na rota', peso:+12,
        fonte:'Report de campo · técnico João Silva',
        detalhe:'Caminhão da Italac visto coletando na Fazenda Bom Jesus (vizinha) em 03/04/2026. Boa Vista mencionou ter recebido proposta verbal.',
        data:'reportado em 04/04/2026' },
      { label:'Sem revisão de bonificação há 11 meses', peso:+8,
        fonte:'Contrato em sistema · ERP',
        detalhe:'Última revisão em 14/06/2025. Política da indústria: revisar a cada 6 meses para produtores categoria Alto.',
        data:'—' },
    ],
    volumeSerie:[4200,4150,4000,3850,3700,3450],
    ccsSerie:[380,420,450,510,590,640],
    visitasTecnicas:[
      { data:'12/04/2026', tecnico:'João Silva (eq. campo Itambé)', achado:'Tanque com defeito no termômetro; rebanho com sinais de subfecundidade. Orientou troca de cortina e revisão do conjunto de ordenha.' },
      { data:'28/02/2026', tecnico:'João Silva', achado:'Acompanhou medição CCS 510. Orientou rotina de pré-dipping mais rigorosa.' },
      { data:'14/12/2025', tecnico:'Mariana Castro', achado:'Visita de rotina; tudo dentro do esperado na ocasião.' },
    ],
    acoesSugeridas:[
      'Visita técnica nos próximos 7 dias para diagnosticar causa da queda de volume.',
      'Revisar bonificação por qualidade — concorrente paga aprox. 8% acima.',
      'Renegociar cláusula contratual nos próximos 30 dias.',
    ],
    ultimoContato:'12/04/2026',
    fontes:['Romaneios diários (ERP)','Laudos de laboratório (CCS/CBT)','Equipe de campo'],
  },
  {
    id:2, nome:'Fazenda Santa Rita', bacia:'Zona da Mata',
    categoria:'Atenção', tendencia:'estável', sobControle:false,
    riskScore:48, confianca:'média', volumeMedio:'5.200 L/dia',
    proprietario:'Marlene Aparecida Coutinho', cpf:'***.207.118-90',
    municipio:'Cataguases · MG', areaHa:78, vinculo:'cooperativa',
    rebanho:{ leiteiras:58, secas:9, raca:'Holandês PO', regime:'Confinado · free stall' },
    contrato:{
      inicio:'10/08/2022', vencimento:'09/08/2026',
      precoBase:2.82, bonificacaoAtual:'CCS<350: +R$ 0,05/L (atinge consistentemente)',
      ultimaRevisaoBonificacao:'10/09/2025',
    },
    motivo:'Italac (concorrente) ativa na rota; sem revisão de bonificação há 8 meses.',
    sinais:[
      { label:'Italac (concorrente) reportada na rota', peso:+20,
        fonte:'Report de campo · técnico João Silva',
        detalhe:'Caminhão da Italac coletando em 2 propriedades vizinhas desde fevereiro/2026.',
        data:'reportado em 11/02/2026' },
      { label:'Sem revisão de bonificação há 8 meses', peso:+15,
        fonte:'Contrato em sistema · ERP',
        detalhe:'Última revisão em 10/09/2025. Produtores categoria Atenção: revisão a cada 6 meses.',
        data:'—' },
      { label:'Volume levemente abaixo da meta (−3%)', peso:+7,
        fonte:'ERP de captação · romaneios diários',
        detalhe:'Meta contratual 5.400 L/dia; média últimos 30 dias 5.230 L/dia (Δ −3,2%).',
        data:'calculado em 28/05/2026' },
    ],
    volumeSerie:[5400,5350,5300,5250,5200,5200],
    ccsSerie:[320,310,330,325,320,315],
    visitasTecnicas:[
      { data:'28/03/2026', tecnico:'João Silva (eq. campo Itambé)', achado:'Produtora comentou que recebeu visita de comprador da Italac. Não topou proposta mas pediu para revisarmos bonificação.' },
      { data:'05/01/2026', tecnico:'João Silva', achado:'Visita de rotina; manejo de free stall exemplar.' },
    ],
    acoesSugeridas:[
      'Antecipar revisão de bonificação para evitar perda gradual.',
      'Reforçar visitas técnicas — produtor estável é mais sensível a oferta concorrente.',
    ],
    ultimoContato:'28/03/2026',
    fontes:['Romaneios diários (ERP)','Equipe de campo','Histórico de contratos'],
  },
  {
    id:3, nome:'Granja Três Irmãos', bacia:'Triângulo Mineiro',
    categoria:'Atenção', tendencia:'subindo', sobControle:false,
    riskScore:55, confianca:'média', volumeMedio:'2.800 L/dia',
    proprietario:'Família Tertuliano (Edson, José e Renato)', cpf:'CNPJ ***.402/0001-77',
    municipio:'Patos de Minas · MG', areaHa:55, vinculo:'cooperativa',
    rebanho:{ leiteiras:32, secas:5, raca:'Girolando 5/8', regime:'Semiconfinado' },
    contrato:{
      inicio:'01/06/2023', vencimento:'31/05/2026',
      precoBase:2.74, bonificacaoAtual:'CCS<400: +R$ 0,04/L',
      ultimaRevisaoBonificacao:'01/12/2025',
    },
    motivo:'Volume oscilando; cooperativa vizinha pagando acima do mercado.',
    sinais:[
      { label:'Cocari (cooperativa concorrente) pagando +R$ 0,04/L na região', peso:+22,
        fonte:'Inteligência de mercado regional · CCPR',
        detalhe:'Boletim interno da CCPR de 22/04/2026 confirma Cocari pagando R$ 2,82/L no Triângulo — acima dos R$ 2,78 da CCPR.',
        data:'levantado em 22/04/2026' },
      { label:'Volume oscilando ±12% nos últimos 4 meses', peso:+14,
        fonte:'ERP de captação · romaneios diários',
        detalhe:'Volume mensal: 2.900 → 3.100 → 2.700 → 3.200 → 2.600 → 2.800 L/dia. CV = 8,3% acima do esperado.',
        data:'calculado em 28/05/2026' },
      { label:'Produtor pediu segunda via de contrato', peso:+10,
        fonte:'Atendimento · CRM',
        detalhe:'Renato Tertuliano ligou em 18/04/2026 pedindo segunda via do contrato. Sinal recorrente de comparação de propostas com concorrente.',
        data:'18/04/2026' },
    ],
    volumeSerie:[2900,3100,2700,3200,2600,2800],
    ccsSerie:[280,295,310,290,305,295],
    visitasTecnicas:[
      { data:'05/04/2026', tecnico:'Marina Couto (CCPR)', achado:'Edson reclamou de pagamento atrasado em fev/26. Demanda corrigida via ERP.' },
    ],
    acoesSugeridas:[
      'Visita imediata — pedido de segunda via é sinal forte de comparação de propostas.',
      'Avaliar bonificação por fidelidade ou bônus de assinatura.',
    ],
    ultimoContato:'05/04/2026',
    fontes:['Romaneios diários (ERP)','Atendimento (CRM)','Inteligência de mercado regional'],
  },
  {
    id:4, nome:'Sítio Recanto', bacia:'Zona da Mata',
    categoria:'OK', tendencia:'caindo', sobControle:false,
    riskScore:12, confianca:'alta', volumeMedio:'1.900 L/dia',
    proprietario:'Antônio Lourenço Mendes', cpf:'***.601.230-45',
    municipio:'Leopoldina · MG', areaHa:28, vinculo:'cooperativa',
    rebanho:{ leiteiras:22, secas:4, raca:'Girolando 1/2', regime:'Extensivo' },
    contrato:{
      inicio:'02/02/2026', vencimento:'01/02/2029',
      precoBase:2.84, bonificacaoAtual:'CCS<300: +R$ 0,08/L (atinge) · CBT<50: +R$ 0,03/L (atinge)',
      ultimaRevisaoBonificacao:'02/02/2026',
    },
    motivo:'Relação estável, qualidade dentro da meta, tendência de risco em queda.',
    sinais:[
      { label:'Volume estável há 6 meses', peso:-8,
        fonte:'ERP de captação · romaneios diários',
        detalhe:'Variação de volume <3% nos últimos 6 meses. Padrão típico de produtor consolidado.',
        data:'calculado em 28/05/2026' },
      { label:'CCS dentro do limite premium (<300)', peso:-6,
        fonte:'Laudo lab. interno (LabAgro Juiz de Fora)',
        detalhe:'CCS médio últimos 6 meses: 264 céls/mL — bem abaixo do limite premium 300.',
        data:'última leitura 19/05/2026' },
      { label:'Contrato renovado em 02/2026 com bonificação atualizada', peso:-10,
        fonte:'Contrato em sistema · ERP',
        detalhe:'Contrato 3 anos vigente. Bonificação atualizada com tier premium + CBT.',
        data:'02/02/2026' },
    ],
    volumeSerie:[1850,1900,1920,1900,1880,1900],
    ccsSerie:[270,265,275,260,255,260],
    visitasTecnicas:[
      { data:'02/05/2026', tecnico:'João Silva (eq. campo Itambé)', achado:'Visita de rotina. Produtor satisfeito com bonificação renegociada em fev/26.' },
    ],
    acoesSugeridas:[
      'Manter ritmo regular de visitas técnicas.',
    ],
    ultimoContato:'02/05/2026',
    fontes:['Romaneios diários (ERP)','Laudos de laboratório'],
  },
  {
    id:5, nome:'Laticínio do Vale', bacia:'Sul de Minas',
    categoria:'OK', tendencia:'estável', sobControle:false,
    riskScore:18, confianca:'alta', volumeMedio:'6.400 L/dia',
    proprietario:'Vale Pecuária Ltda. (família Reis)', cpf:'CNPJ ***.118/0001-23',
    municipio:'Três Corações · MG', areaHa:210, vinculo:'cooperativa',
    rebanho:{ leiteiras:72, secas:14, raca:'Holandês PO', regime:'Confinado · free stall' },
    contrato:{
      inicio:'01/12/2024', vencimento:'30/11/2026',
      precoBase:2.86, bonificacaoAtual:'CCS<300: +R$ 0,10/L · Volume crescente: +R$ 0,03/L',
      ultimaRevisaoBonificacao:'01/12/2025',
    },
    motivo:'Contrato vigente, sem sinais de saída.',
    sinais:[
      { label:'Contrato anual vigente até 11/2026', peso:-12,
        fonte:'Contrato em sistema · ERP',
        detalhe:'Faltam 6 meses para vencimento. Bonificação tier premium ativa.',
        data:'—' },
      { label:'Volume crescendo +2%/mês (expansão de rebanho)', peso:-5,
        fonte:'ERP de captação + relato do produtor',
        detalhe:'Volume mensal: 6.100 → 6.180 → 6.240 → 6.310 → 6.360 → 6.400 L/dia. Família comprou 18 vacas em 02/2026.',
        data:'calculado em 28/05/2026' },
      { label:'Sem registro de concorrente ativo na rota', peso:-6,
        fonte:'Report de campo · técnico Eduardo Stein',
        detalhe:'Rota Três Corações–Varginha sem registro de coleta concorrente nos últimos 90 dias.',
        data:'verificado em 15/05/2026' },
    ],
    volumeSerie:[6100,6180,6240,6310,6360,6400],
    ccsSerie:[295,290,295,285,290,288],
    visitasTecnicas:[
      { data:'20/04/2026', tecnico:'Eduardo Stein (Cooxupé Leite)', achado:'Família Reis apresentou plano de expansão pra 90 vacas até dez/26. Oportunidade de crescer volume contratado.' },
    ],
    acoesSugeridas:[
      'Acompanhar plano de expansão do rebanho — oportunidade de crescer volume contratado.',
    ],
    ultimoContato:'20/04/2026',
    fontes:['Romaneios diários (ERP)','Histórico de contratos','Equipe de campo'],
  },
];

/* Opções de selects/dropdowns no formulário CRUD de produtor */
const PRODUTOR_OPCOES = {
  racas:['Holandês PO','Holandês × Gir (3/4)','Girolando 5/8','Girolando 1/2','Jersey','Pardo Suíço','Outra'],
  regimes:['Extensivo','Semiconfinado','Confinado · free stall','Confinado · compost barn'],
  vinculos:['cooperativa','direto com a indústria'],
};
const ALERTA_CONCORRENCIA = 'Movimentação da Italac (concorrente) reportada por técnicos de campo em 4 rotas da Zona da Mata. Atenção.';

const COOPERATIVA_ITAMBE = {
  nome:'Itambé',
  chuva:'CHIRPS: chuva 18% abaixo da média de 10 anos na região da cooperativa.',
  projecao:'Produção regional projetada -6% no próximo trimestre (modelo de oferta).',
  secasComparaveis:['Seca de 2014 (oferta -8%)','Seca de 2021 (oferta -5%)'],
  resumoPreConversa:[
    'Chuva acumulada na região caiu 18% vs. média de 10 anos.',
    'Projeção de oferta regional -6% nos próximos 3 meses — pressão de captação à frente.',
    'Qualidade do leite (CCS) subindo, como esperado na seca.',
    'Última cláusula contratual de preço foi negociada há 7 meses.',
  ],
  // Argumentos estruturados — para defender a decisão na reunião com a cooperativa
  pontosDefesa:[
    {
      titulo:'Antecipar revisão protege os dois lados, não só a indústria',
      argumento:'A indústria garante suprimento sem disputa de spot price; a cooperativa trava preço antes do pico de demanda da seca e captura prêmio sem confrontar produtor.',
      dadosSuporte:[
        'CHIRPS: chuva 18% abaixo da média 10 anos · projeção CHIRPS jul–ago: -27% vs. base',
        'Seca de 2014 (padrão similar): oferta regional caiu 8% e preço subiu R$ 0,07/L',
        'Última cláusula de preço foi negociada em 14/10/2025 (há 7 meses)',
      ],
    },
    {
      titulo:'Cláusula de gatilho climático elimina risco de erro de previsão',
      argumento:'Em vez de discutir agora o quanto subir, definimos um gatilho automático: se CHIRPS de jul–ago confirmar >25% abaixo, a janela extraordinária abre. Se não confirmar, mantém status quo. Ninguém sai apostando.',
      dadosSuporte:[
        'CHIRPS publica diariamente · dado público auditável',
        'Modelo já usado em contratos de soja e milho na safra 24/25',
        'Reduz peso da reunião — a leitura técnica decide, não o jogo de poder',
      ],
    },
    {
      titulo:'Tier CCS<300 incentiva o produtor a investir antes da seca apertar',
      argumento:'Travar +R$ 0,10/L para CCS<300 agora — quando o produtor ainda tem caixa pré-seca — vira proteção de qualidade no pico da estiagem. Custo marginal pra Itambé, ganho de mix premium pra indústria.',
      dadosSuporte:[
        'CCS regional subiu 12% nos últimos 90 dias',
        'Histórico: produtores que receberam tier pré-seca em 2021 mantiveram CCS<300 em 78% do período',
      ],
    },
    {
      titulo:'Aumento de volume contratado em +12% é absorvível pela base atual',
      argumento:'Nossa projeção mostra que 148 produtores ativos × volume médio crescente pode entregar 318k L/dia sem demandar captação extra. Cooperativa não precisa correr atrás de novos produtores no curto prazo.',
      dadosSuporte:[
        'Volume atual: 284.500 L/dia · capacidade técnica estimada: 325k L/dia',
        'Tendência de volume últimos 7 meses: +8,5% (orgânico)',
      ],
    },
  ],
  // Contra-argumentos antecipados — "se ele disser X, responda Y"
  contraargumentos:[
    {
      vemDeles:'"O CHIRPS pode estar errado. Vamos esperar mais 30 dias pra ter certeza."',
      respondaCom:'Cláusula de gatilho automático resolve. A revisão só dispara se o dado confirmar — quem estiver errado paga o custo zero. Mas se esperarmos 30 dias e o sinal fechar, perdemos a janela de planejamento.',
    },
    {
      vemDeles:'"Vocês querem antecipar pra forçar bônus menor antes da escassez."',
      respondaCom:'Pelo contrário — proponho travar bonificação CCS<300 em +R$ 0,10/L já. A indústria assume o custo da bonificação antes da seca apertar. Se o objetivo fosse forçar bônus menor, esperaríamos a oferta ficar curta.',
    },
    {
      vemDeles:'"Mas o Rabobank diz que o mercado vai cair 2% no semestre."',
      respondaCom:'O Rabobank cobre o mercado nacional. Nossa leitura é regional — CHIRPS na sua área específica está 18% abaixo. Históricamente, quando discordamos do Rabobank com base em dado climático regional, acertamos 64% das vezes (transparência disponível).',
    },
    {
      vemDeles:'"Precisamos discutir o tier de bonificação separadamente."',
      respondaCom:'Razoável. Podemos fechar a antecipação de volume + gatilho climático nesta reunião e marcar uma segunda em 15 dias só para o tier de qualidade. Mostra que cada peça tem critério próprio.',
    },
  ],
  roteiroConversa:{
    abertura:'Não vim apresentar número — vim apresentar uma leitura nova de oferta regional que pode reforçar a parceria pros dois lados. Posso compartilhar?',
    centro:'Mostrar dado CHIRPS + comparativo histórico (2014) + impacto na janela de captação. Propor cláusula de gatilho automático. Listar +12% volume como derivada, não como pedido inicial.',
    fechamento:'Posso voltar com proposta formal de cláusula de gatilho na próxima semana? E a gente marca tier de bonificação pra 2 semanas depois?',
  },
  pontosEvitar:[
    'Não propor valor de bonificação fora dos tiers atuais sem revisão interna prévia da indústria.',
    'Não mencionar Italac (concorrente) — pode soar como ameaça e queimar a confiança da Itambé.',
    'Não comprometer +12% de volume sem antes confirmar capacidade fabril de processar.',
    'Não jogar previsão de IA como verdade absoluta — apresentar como leitura técnica com banda de incerteza.',
  ],
};

const AUDITORIA = {
  acertoHorizonte:{ '1T':78, '2T':72, '3T':61 },
  acertoPilar:{ 'Climático':81, 'Econômico':68, 'Agropecuário':74, 'Político':null },
  acertoDivergencia:64,
  acertoEmRecusa:{ acertos:3, total:4 },
  log:[
    /* ──────────────── Zona da Mata · 13 entradas · 10 ok = 77% ────────────────
       Climático 5 ent / 4 ok = 80% · Econômico 5 ent / 4 ok = 80% · Agropecuário 3 ent / 2 ok = 67%
       1T 5 ent / 4 ok = 80% · 2T 5 ent / 4 ok = 80% · 3T 3 ent / 2 ok = 67% */
    { data:'10/05/2026', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Climático',    realizado:+0.05, ok:true },
    { data:'22/03/2026', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Econômico',    realizado:+0.03, ok:true },
    { data:'20/02/2026', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Climático',    realizado:+0.04, ok:true },
    { data:'05/01/2026', bacia:'Zona da Mata',     decisao:'Ajustado', por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Climático',    justificativa:'Calibrar peso do milho', realizado:+0.02, ok:true },
    { data:'18/11/2025', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Agropecuário', realizado:+0.03, ok:true },
    { data:'02/10/2025', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Econômico',    realizado:-0.01, ok:false },
    { data:'02/09/2025', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Climático',    realizado:-0.01, ok:false },
    { data:'14/08/2025', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Agropecuário', realizado:+0.04, ok:true },
    { data:'14/06/2025', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Econômico',    realizado:+0.03, ok:true },
    { data:'15/03/2025', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Climático',    realizado:+0.04, ok:true },
    { data:'18/02/2025', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'3T', pilarDominante:'Econômico',    realizado:+0.03, ok:true },
    { data:'08/12/2024', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Econômico',    realizado:+0.02, ok:true },
    { data:'12/09/2024', bacia:'Zona da Mata',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Agropecuário', realizado:+0.01, ok:false },

    /* ──────────────── Triângulo Mineiro · 13 entradas · 7 ok = 54% (baixa confiança) ────────────────
       Climático 5 / 3 ok = 60% · Econômico 4 / 2 ok = 50% · Agropecuário 4 / 2 ok = 50%
       1T 5 / 3 ok = 60% · 2T 5 / 3 ok = 60% · 3T 3 / 1 ok = 33% */
    { data:'15/03/2026', bacia:'Triângulo Mineiro',decisao:'Ajustado', por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Climático',    justificativa:'Clima neutro, não La Niña', realizado:+0.01, ok:true },
    { data:'08/12/2025', bacia:'Triângulo Mineiro',decisao:'Recusado', por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Agropecuário', justificativa:'Risco operacional alto', realizado:+0.02, ok:false },
    { data:'22/10/2025', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Econômico',    realizado:-0.02, ok:false },
    { data:'15/08/2025', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Agropecuário', realizado:+0.02, ok:true },
    { data:'05/05/2025', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Climático',    realizado:+0.02, ok:true },
    { data:'18/03/2025', bacia:'Triângulo Mineiro',decisao:'Ajustado', por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Climático',    justificativa:'Pondera Cocari', realizado:+0.01, ok:true },
    { data:'02/02/2025', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Econômico',    realizado:+0.02, ok:true },
    { data:'15/11/2024', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Agropecuário', realizado:+0.02, ok:true },
    { data:'04/08/2024', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'3T', pilarDominante:'Climático',    realizado:-0.01, ok:false },
    { data:'18/05/2024', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Climático',    realizado:+0.02, ok:true },
    { data:'10/02/2024', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Econômico',    realizado:+0.01, ok:true },
    { data:'12/11/2023', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Agropecuário', realizado:+0.02, ok:true },
    { data:'08/08/2023', bacia:'Triângulo Mineiro',decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Climático',    realizado:0.00, ok:false },

    /* ──────────────── Sul de Minas · 13 entradas · 10 ok = 77% (premium consistente) ────────────────
       Climático 5 / 4 ok = 80% · Econômico 4 / 3 ok = 75% · Agropecuário 4 / 3 ok = 75%
       1T 5 / 4 ok = 80% · 2T 5 / 4 ok = 80% · 3T 3 / 2 ok = 67% */
    { data:'28/04/2026', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Agropecuário', realizado:+0.04, ok:true },
    { data:'18/02/2026', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Climático',    realizado:+0.03, ok:true },
    { data:'14/01/2026', bacia:'Sul de Minas',     decisao:'Ajustado', por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Econômico',    justificativa:'Câmbio acima do projetado', realizado:+0.03, ok:true },
    { data:'22/10/2025', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Climático',    realizado:+0.02, ok:true },
    { data:'15/07/2025', bacia:'Sul de Minas',     decisao:'Recusado', por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Agropecuário', justificativa:'Cooperativa em revisão de gestão', realizado:0.00, ok:true, recusaCorreta:true },
    { data:'02/05/2025', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Climático',    realizado:+0.05, ok:true },
    { data:'10/02/2025', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Econômico',    realizado:+0.01, ok:false },
    { data:'08/11/2024', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Agropecuário', realizado:+0.03, ok:true },
    { data:'15/08/2024', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'3T', pilarDominante:'Climático',    realizado:0.00, ok:false },
    { data:'22/04/2024', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Econômico',    realizado:+0.02, ok:true },
    { data:'18/02/2024', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Climático',    realizado:+0.01, ok:false },
    { data:'14/11/2023', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Agropecuário', realizado:+0.01, ok:false },
    { data:'05/08/2023', bacia:'Sul de Minas',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Econômico',    realizado:+0.02, ok:true },

    /* ──────────────── Sul de Goiás · 13 entradas · 9 ok = 69% (defensivo, decente) ────────────────
       Climático 5 / 3 ok = 60% · Econômico 4 / 3 ok = 75% · Agropecuário 4 / 3 ok = 75%
       1T 5 / 3 ok = 60% · 2T 5 / 4 ok = 80% · 3T 3 / 2 ok = 67% */
    { data:'02/04/2026', bacia:'Sul de Goiás',     decisao:'Recusado', por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Econômico',    justificativa:'Câmbio vai virar', realizado:-0.03, ok:true, recusaCorreta:true },
    { data:'12/11/2025', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'3T', pilarDominante:'Econômico',    realizado:+0.01, ok:false },
    { data:'25/08/2025', bacia:'Sul de Goiás',     decisao:'Recusado', por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Climático',    justificativa:'Sinal climático muito incerto', realizado:-0.01, ok:true, recusaCorreta:true },
    { data:'18/06/2025', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'3T', pilarDominante:'Agropecuário', realizado:-0.02, ok:true },
    { data:'22/03/2025', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Climático',    realizado:-0.04, ok:true },
    { data:'10/01/2025', bacia:'Sul de Goiás',     decisao:'Ajustado', por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Agropecuário', justificativa:'Concentrar produtores OK', realizado:+0.02, ok:false },
    { data:'15/10/2024', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Econômico',    realizado:-0.03, ok:true },
    { data:'05/07/2024', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Climático',    realizado:+0.01, ok:false },
    { data:'18/04/2024', bacia:'Sul de Goiás',     decisao:'Recusado', por:'Carlos Mendes',   horizonte:'3T', pilarDominante:'Climático',    justificativa:'Padrão sazonal histórico', realizado:-0.02, ok:true, recusaCorreta:true },
    { data:'10/02/2024', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Agropecuário', realizado:-0.02, ok:true },
    { data:'15/11/2023', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Econômico',    realizado:+0.01, ok:false },
    { data:'08/08/2023', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Climático',    realizado:+0.01, ok:false },
    { data:'04/05/2023', bacia:'Sul de Goiás',     decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Agropecuário', realizado:-0.01, ok:true },

    /* ──────────────── Norte do Paraná · 13 entradas · 9 ok = 69% (sinal baixo, acerto medio) ────────────────
       Climático 5 / 3 ok = 60% · Econômico 4 / 3 ok = 75% · Agropecuário 4 / 3 ok = 75%
       1T 5 / 3 ok = 60% · 2T 5 / 4 ok = 80% · 3T 3 / 2 ok = 67% */
    { data:'18/03/2026', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Climático',    realizado:-0.01, ok:false },
    { data:'25/10/2025', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Agropecuário', realizado:+0.02, ok:true },
    { data:'05/08/2025', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Econômico',    realizado:+0.02, ok:true },
    { data:'12/06/2025', bacia:'Norte do Paraná',  decisao:'Ajustado', por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Climático',    justificativa:'Padrão estável de PR', realizado:+0.02, ok:true },
    { data:'04/04/2025', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Agropecuário', realizado:+0.01, ok:true },
    { data:'08/02/2025', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'3T', pilarDominante:'Climático',    realizado:0.00, ok:false },
    { data:'14/11/2024', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Anderson Toledo', horizonte:'2T', pilarDominante:'Econômico',    realizado:+0.02, ok:true },
    { data:'22/08/2024', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'1T', pilarDominante:'Climático',    realizado:+0.01, ok:false },
    { data:'05/05/2024', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Anderson Toledo', horizonte:'3T', pilarDominante:'Agropecuário', realizado:+0.01, ok:true },
    { data:'18/02/2024', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Climático',    realizado:+0.02, ok:true },
    { data:'12/11/2023', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Econômico',    realizado:+0.02, ok:true },
    { data:'08/08/2023', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Carlos Mendes',   horizonte:'2T', pilarDominante:'Agropecuário', realizado:+0.03, ok:true },
    { data:'15/04/2023', bacia:'Norte do Paraná',  decisao:'Aceito',   por:'Anderson Toledo', horizonte:'1T', pilarDominante:'Econômico',    realizado:-0.01, ok:false },
  ],
  recalibracao:'A IA recalibrou automaticamente o peso do milho futuro depois que você discordou no ciclo de março/2026 e estava certo.',
  escalonamento:'Você está em 55% de recusa neste trimestre (em recomendações de alto impacto). O sistema sugere uma revisão antes que o assunto chegue à diretoria — para reagir antes, não ser pego de surpresa.',
};

const HIPOTESE_IMPACTO = 'Exemplo de promessa mensurável: numa região leiteira como a Zona da Mata mineira, a IA do Vereda projetaria um ganho de R$ 0,03 a R$ 0,08 por litro vs. o preço de referência do mercado (CEPEA), com 65% de probabilidade, em 6 meses. Cada região teria sua própria estimativa, calibrada com dados locais.';
const CHAT_SUGGESTIONS = [
  {
    q: 'Qual região tem maior chance de vantagem de preço nos próximos 6 meses?',
    a: 'Zona da Mata (MG) — previsão de +R$ 0,06/litro acima do preço CEPEA com 70% de probabilidade. O acerto histórico em 6 meses nessa região é de 72%. Principal motivo: chuva 18% abaixo da média (CHIRPS) deve reduzir a oferta regional. Veja detalhes em "Painel por região".'
  },
  {
    q: 'Por que a IA recomenda antecipar negociação com a Itambé?',
    a: 'Três fatores se somam: (1) chuva abaixo da média na região da cooperativa, projetando -6% de oferta no próximo trimestre; (2) dólar a R$ 5,40 e milho +3% pressionando custo do produtor; (3) última cláusula contratual foi negociada há 7 meses. Detalhamento por fator em "Recomendações" > Zona da Mata.'
  },
  {
    q: 'E se o dólar cair para R$ 4,80? Como muda a previsão?',
    a: 'Dólar a R$ 4,80 reduziria a previsão da Zona da Mata em cerca de R$ 0,05/litro (de +R$ 0,06 para perto de +R$ 0,01). O motivo: dólar mais baixo torna o leite em pó importado mais competitivo e enfraquece o preço doméstico. Teste essa hipótese no "Simulador".'
  },
  {
    q: 'A IA já errou alguma vez? Quanto?',
    a: 'Sim. Em previsões de 6 meses, a IA acerta 72% das vezes; em 9 meses, cai para 61%. O fator que mais erra é o Econômico (68% de acerto). O fator Político fica em quarentena e não entra no cálculo. Métricas completas em "Transparência da IA".'
  },
  {
    q: 'Em que a IA do Vereda discorda dos analistas de mercado?',
    a: 'O Rabobank projeta -2% no mercado geral no semestre. A IA do Vereda discorda especificamente para a Zona da Mata (+R$ 0,02/litro), com base em dados climáticos locais (CHIRPS) que o Rabobank não usa. Quando a IA discorda dos analistas de referência, acerta 64% das vezes — métrica em "Transparência da IA".'
  }
];

const FONTES_REAIS = [
  { nome:'CEPEA/ESALQ', uso:'Preço de referência do leite no Brasil', url:'https://www.cepea.esalq.usp.br/br/indicador/leite.aspx' },
  { nome:'BCB-SGS', uso:'Câmbio, séries econômicas (Banco Central)', url:'https://www3.bcb.gov.br/sgspub/' },
  { nome:'NASA POWER', uso:'Dados climáticos por satélite, grade ~5km', url:'https://power.larc.nasa.gov/' },
  { nome:'CHIRPS', uso:'Chuva por satélite, atualização diária', url:'https://www.chc.ucsb.edu/data/chirps' },
  { nome:'INMET', uso:'Estações meteorológicas brasileiras', url:'https://portal.inmet.gov.br/' },
  { nome:'CONAB', uso:'Safra, oferta agrícola nacional', url:'https://www.conab.gov.br/' },
  { nome:'IBGE PPM', uso:'Rebanho e produção pecuária municipal', url:'https://www.ibge.gov.br/' },
  { nome:'MAPA', uso:'Decisões sanitárias, tributárias, Diário Oficial', url:'https://www.gov.br/agricultura/' },
  { nome:'Global Dairy Trade', uso:'Preço internacional de lácteos', url:'https://www.globaldairytrade.info/' },
];
